[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.0"
async-graphql = "5.0.5"
async-graphql-actix-web = "5.0.5"
chrono = "0.4.23"
color-eyre = "0.6.2"
env_logger = "0.10.0"
eyre = "0.6.8"
futures-util = "0.3.26"
serde_json = "1.0.91"
slab = "0.4.7"
tracing = "0.1.37"
